# Generated by Django 5.2.8 on 2025-11-28 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='course code')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, verbose_name='day of week')),
                ('time_slot', models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('14-16', '14:00 - 16:00'), ('16-18', '16:00 - 18:00')], max_length=10, verbose_name='time slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='courses.course', verbose_name='prerequisites')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
    ]
