# Generated by Django 5.2.8 on 2025-11-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='course',
            name='location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='time_slot',
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, verbose_name='day of week')),
                ('time_slot', models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('14-16', '14:00 - 16:00'), ('16-18', '16:00 - 18:00')], max_length=10, verbose_name='time slot')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course schedule',
                'verbose_name_plural': 'course schedules',
                'unique_together': {('course', 'day_of_week', 'time_slot')},
            },
        ),
    ]
