# Generated by Django 5.2.8 on 2025-11-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_day_of_week_remove_course_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, verbose_name='day of week'),
        ),
    ]
